SWDEV-502603 - Use RPM_INSTALL_PREFIX variable rather than hard coded install prefix paths in RPM post/prerm scripts
Change-Id: I2699459e1e3730cf045f24f0c90e09f900701a6f


[ROCm/rdc commit: b778a879cbb75b122e4583b347c4b54385ef5579]

diff --git a/src/RPM_rpm_post.in b/src/RPM_rpm_post.in
--- a/src/RPM_rpm_post.in
+++ b/src/RPM_rpm_post.in
@@ -40,12 +40,12 @@ do_update_alternatives(){
     do
         # No obvious recover strategy if things fail
         # No manual or other slave pages to install
-        if [ -e @CPACK_PACKAGING_INSTALL_PREFIX@/@CMAKE_INSTALL_BINDIR@/"$i" ]
+        if [ -e $RPM_INSTALL_PREFIX0/@CMAKE_INSTALL_BINDIR@/"$i" ]
         then
             update-alternatives --install /usr/bin/"$i" "$i" \
-                                @CPACK_PACKAGING_INSTALL_PREFIX@/@CMAKE_INSTALL_BINDIR@/"$i" "$altscore"
+                                $RPM_INSTALL_PREFIX0/@CMAKE_INSTALL_BINDIR@/"$i" "$altscore"
         else
-            echo "@CPACK_PACKAGING_INSTALL_PREFIX@/@CMAKE_INSTALL_BINDIR@/$i not found, but that is OK" >&2
+            echo "$RPM_INSTALL_PREFIX0/@CMAKE_INSTALL_BINDIR@/$i not found, but that is OK" >&2
         fi
     done
     true
@@ -78,7 +78,7 @@ do_create_rdc_user() {
 
 create_rdc_service() {
     if [ -d /run/systemd/system ]; then
-        ln -s -f -r @CPACK_PACKAGING_INSTALL_PREFIX@/@CMAKE_INSTALL_LIBEXECDIR@/rdc/rdc.service @DISTRO_ROOT@/rdc.service
+        ln -s -f -r $RPM_INSTALL_PREFIX0/@CMAKE_INSTALL_LIBEXECDIR@/rdc/rdc.service @DISTRO_ROOT@/rdc.service
     fi
 }
 
