SWDEV-500830 add building and running examples
Signed-off-by: adapryor <Adam.pryor@amd.com>
Change-Id: I976e999d4a9f4a22730542df95f50549f58ad317
Signed-off-by: adapryor <Adam.pryor@amd.com>

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -179,3 +179,25 @@ jobs:
         else
           echo "No missing libs found!"
         fi
+
+    - name: Build RDC Examples
+      shell: bash
+      run: |
+        cd /opt/rocm/share/rdc/example
+        cmake -B build
+        make -C build -j $(nproc)
+      
+    - name: Test RDC Examples
+      shell: bash
+      run: |
+        cd /opt/rocm/share/rdc/example/build
+        for example in ./diagnostic ./fieldvalue ./jobstats ./rocprofiler; do
+          echo "Testing $example..."
+          echo 0 | $example
+          if [ $? -ne 0 ]; then
+            echo "Example $example failed!"
+            exit 1
+          fi
+        done
+        echo "All examples ran successfully!"
+    
